### ISSUE TITLE
Possible issue around span's scope

### ISSUE THREAD

**Issue by bwidawsk** [nagisa/rust_tracy_client#64]
I am having a hard time figuring out if this is caused by the bindings, or tracy itself.

The following will cause the tracy client to print: `Instrumentation failure: Invalid order of zone begin and end events.`
```
            if let Some(fd) = fence_fd {
                let mut fence_span = Some(tracing_tracy::client::span!("Wait for fence"));
                let _ = self.loop_handle.insert_source(
                    Generic::new(fd, Interest::READ, calloop::Mode::Level),
                    move |_, _, _| {
                        drop(fence_span.take());
                        Ok(PostAction::Remove)
                    },
                );
            }
```

As far as I can tell, this should be perfectly fine to do, but it doesn't work.

**Comment by nagisa** [comment]
Without a more minimal, and more importantly, self-contained reproducer this is going to be hard to advise on or to investigate.

That said, Tracy has a boatload of limitations around how it expects zones (spans) to be structured. One particular requirement is that zones must form a tree, meaning that children zones must enter and exit entirely within the confines of the parent zone activity. Since you’re using the `tracy-client` API directly, rather than through `tracing`, it is up to yourself to ensure that you instrument your program the way Tracy expects.

If I had to guess what happens is that the "Wait for fence" span is entered multiple times and they are exited in an unpredictable order, thus failing to form a tree of children zones.

(In contrast `tracing` is much more flexible – to the point where you can have entirely disjoint spans in the same thread. The `tracing` integrations attempt to work within these limitations at the tradeoff that some profiles will produce semi-invalid data (with an indication that it has happened.) But there are limits to how much we can do there.)

**Comment by bwidawsk** [comment]
Thanks for the write-up. I'll close since there's reasonable evidence this is my bug.
